[package]
name = "findout"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = { version = "25.0.1", features = ["chrono"] }
clap = { version = "4.1.8", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
